services:
  postgres:
    image: postgres:17.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: soulbound
      POSTGRES_USER: soulbound
      POSTGRES_PASSWORD: user123
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data:
      